// CSV export labels for the operational reports, per app language (client
// template alignment: downloads follow the user's selected language).
const LABELS = {
  en: {
    vehicleName: "Vehicle",
    vehicleNumber: "Registration No.",
    totalTrips: "Trips",
    totalKm: "Distance (km)",
    fuelCost: "Fuel Cost",
    maintenanceCost: "Maintenance Cost",
    insuranceCost: "Insurance Cost",
    totalCost: "Total Cost",
    costPerTrip: "Cost per Trip",
    costPerKm: "Cost per km",
    staffId: "Staff ID",
    staffName: "Staff Name",
    month: "Month",
    year: "Year",
    forecastDays: "Forecasted Days",
    actualDays: "Actual Days",
    forecastHours: "Forecasted Hours",
    actualHours: "Actual Hours",
    absentDays: "Absent Days",
    varianceDays: "Variance Days",
    varianceHours: "Variance Hours",
    dayStatus: (d) => `Day ${d} Status`,
    dayHours: (d) => `Day ${d} Hours`,
    monthName: (m, name) => name,
    bookingId: "Booking ID",
    participantId: "Participant ID",
    participantName: "Participant Name",
    guardianName: "Guardian Name",
    serviceType: "Service Type",
    bookingDate: "Booking Date",
    serviceDate: "Service Date",
    status: "Status",
    pickup: "Pickup Location",
    dropoff: "Dropoff Location",
    duration: "Duration",
    notes: "Notes",
    approvedBy: "Approved By",
    rejectedReason: "Rejected Reason",
    statusValue: { PENDING: "Pending", APPROVED: "Approved", REJECTED: "Rejected", CANCELLED: "Cancelled", COMPLETED: "Completed", WAITLISTED: "Waitlisted" },
    serviceTypeValue: { MOBILITY: "Mobility Support", RECREATION: "Recreation", DAYCARE: "Daytime Support" },
  },
  ja: {
    vehicleName: "車両",
    vehicleNumber: "車両番号",
    totalTrips: "運行回数",
    totalKm: "走行距離（km）",
    fuelCost: "燃料費",
    maintenanceCost: "整備費",
    insuranceCost: "保険料",
    totalCost: "合計費用",
    costPerTrip: "1回あたり費用",
    costPerKm: "1kmあたり費用",
    staffId: "スタッフID",
    staffName: "スタッフ名",
    month: "月",
    year: "年",
    forecastDays: "予測日数",
    actualDays: "実績日数",
    forecastHours: "予測時間",
    actualHours: "実績時間",
    absentDays: "欠勤日数",
    varianceDays: "差異日数",
    varianceHours: "差異時間",
    dayStatus: (d) => `${d}日 状況`,
    dayHours: (d) => `${d}日 時間`,
    monthName: (m) => `${m}月`,
    bookingId: "予約ID",
    participantId: "参加者ID",
    participantName: "参加者名",
    guardianName: "保護者名",
    serviceType: "サービス種別",
    bookingDate: "予約日",
    serviceDate: "サービス日",
    status: "状態",
    pickup: "乗車場所",
    dropoff: "降車場所",
    duration: "所要時間",
    notes: "備考",
    approvedBy: "承認者",
    rejectedReason: "却下理由",
    statusValue: { PENDING: "保留中", APPROVED: "承認済", REJECTED: "却下", CANCELLED: "キャンセル", COMPLETED: "完了", WAITLISTED: "キャンセル待ち" },
    serviceTypeValue: { MOBILITY: "移動支援", RECREATION: "レクリエーション", DAYCARE: "日中支援" },
  },
};

const getLabels = (lang) => LABELS[lang === "ja" ? "ja" : "en"];

module.exports = { getLabels };
